monolog:
    handlers:
        main:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: info  # Cambia esto a 'info' para evitar los logs de debug
            channels: ["!event"]